### ISSUE TITLE
Running basicbot?

### ISSUE THREAD

**Issue by Botanistt** [plugCubed/plugAPI#104]
How to run basic bot with this?

**Comment by Botanistt** [comment]
I mean hosting it on linux machine so bot is active 24/7.
Since you can do this with plugAPI I was wondering if theres a way to run basicbot with it.

**Comment by Hunchmun** [comment]
You can run it with phantomjs, or you could install a desktop environment
and run it in Firefox on that server through VNC.

Both are a little outside of the scope of support basicbot, ideally you
would use a library such as plugapi and write your own bot with it if you
wanted to server host it.
On 7 Jun 2016 9:41 a.m., "Botanistt" <notifications@github.com> wrote:

I mean hosting it on linux machine so bot is active 24/7.
Since you can do this with plugAPI I was wondering if theres a way to run
basicbot with it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/plugCubed/plugAPI/issues/104#issuecomment-224216845>,
or mute the thread
<https://github.com/notifications/unsubscribe/AF-75II6gnAHf6jSBJPfmNbEbWuh8kDpks5qJS7IgaJpZM4IvKc->
.

**Comment by Botanistt** [comment]
Thanks @Hunchmun !
