### ISSUE TITLE
getPlaylists callback argument is not a RESTCallback

### ISSUE THREAD

**Issue by mortenn** [plugCubed/plugAPI#146]
The callback argument for getPlaylists is of the form `(data) => {}`, not `(err, data) => {}` as is the norm for other methods in the API.

**Comment by thedark1337** [comment]
yes, because its stored in a buffer object that doesn't result in an error. Its not the only function that isnt in the (err, data) => {} format.

getHistory
getActivePlaylist
getPlaylist
getPlaylists
getJar

These all don't use API methods to send a REST request and are documented to have the standard function callback style. All of them are cached in their respective locations in plugAPI itself.

**Comment by mortenn** [comment]
I kind of like it when APIs are consistent, would you be opposed to change them?
As a better alternative, if they returned a Promise, I wouldn't need to wrap them at all :)

**Comment by thedark1337** [comment]
Changing them would break any user's code that uses callbacks unfortunately. I can't just change it to return callback(null, data);

**Comment by mortenn** [comment]
Returning a promise shouldn't break anyone, I think?

**Comment by Hunchmun** [comment]
Changing to promises requires a large discussion on the direction of plugcubed

**Comment by thedark1337** [comment]
Regarding the discussion on promise usage, that will be moved to #144.
As for this issue, RESTCallback as its named is in the form of error, data for API REST calls. 

For those that are just pure setters / getters with no interaction with the REST API, those only return callback(data) or data.
