### ISSUE TITLE
TypeError: Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by ayatojhans** [plugCubed/plugAPI#74]
Happens at random times, without any action or user input taking place. What does this mean?
```
TypeError: Cannot call method 'split' of undefined
    at Request._callback (/app/node_modules/plugapi/bin/src/client.js:989:21)
    at Request.self.callback (/app/node_modules/request/request.js:368:22)
    at Request.<anonymous> (/app/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at Request.emit (events.js:98:17)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1167:12)
    at process._tickCallback (node.js:448:13)
    at Function.module.exports.runLoopOnce (/app/node_modules/plugapi/node_modules/deasync/index.js:54:10)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by thedark1337** [comment]
That's usually when plug disconnects you and it tries to reconnect and can't get the session data needed to connect.

We login via a request to plug's site that splits the body and gets the CSRF token to login. Sometimes it cant find this token because a connection to plug.dj was made but it was during their Maintenance mode or maybe some other error where the token can't be found.

**Comment by ayatojhans** [comment]
Ok so, from what I understand, it's something that can't be avoided, right?

Is there a way to sort of catch the error or something similar, so the app doesn't crash?

**Comment by thedark1337** [comment]
There is a way to catch it but if plug is down for maintenance mode or some other issue and it we make it not crash, then you'd be constantly reconnecting to plug until its back up and you can get in.

I'm not 100% sure that is a good idea to do.

**Comment by ayatojhans** [comment]
You're talking about making plugAPI catch the error, like in the core, right? And that might not be a good idea.

However, is there a way for us (building a bot for example) to catch it?

**Comment by thedark1337** [comment]
Yes I am talking about the core.

What happens when plugAPI tries to reconnect to plug is it sends a request every few seconds to try to reconnect. If we have it constantly reconnecting during maintenance or when the site is down, that is sending unneeded requests imho. 

Their Maintenance mode is always 200 HTTP status which means i can't really add a way to reliably check if they are in Maint or not. I can always check if the site is other HTTP statuses however, but I'm not sure if that will fix the issue.

There is not currently a way for you, the creator of a bot to catch this error and handle it

**Comment by ayatojhans** [comment]
Damn =/ I'm sure I'm not the only one dealing with how plug's API is architectured.

Oh well, thanks for the explanation. :)
